substitutions:
  tx_pin: GPIO16
  rx_pin: GPIO17

esphome:
  name: econet-hpwh
  friendly_name: Water Heater
  comment: Rheem Heat Pump Water Heater
  min_version: 2025.5.0
  project:
    name: esphome-econet.esphome-econet
    version: v3.0.2

esp32:
  board: esp32dev

packages:
  econet:
    url: https://github.com/esphome-econet/esphome-econet
    ref: main
    file: econet_heatpump_water_heater.yaml

dashboard_import:
  package_import_url: github://esphome-econet/esphome-econet/build-yaml/${name}-${platform}.yaml@${github_ref}
  import_full_config: false

ethernet:
  type: IP101
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO0_IN
  phy_addr: 1
  power_pin: GPIO5

wifi: !remove
captive_portal: !remove

web_server:
  port: 80
  local: true

sensor:
  - id: !remove wifi_signal_sensor
